spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true